include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true

linter:
  rules:
    - unawaited_futures
    - avoid_dynamic_calls
    - cancel_subscriptions
    - close_sinks
    - no_adjacent_strings_in_list
    - throw_in_finally
    - control_flow_in_finally
    - test_types_in_equals
    - avoid_slow_async_io
    - unnecessary_statements
